PRODUCTS = [
    {
        "display_order": 1,
        "sku": "CLD-01",
        "name": "คลอดต้า 1",
        "price": 990.00,
        "pv": 166.67,
        "description": "แพ็กเริ่มต้นที่ขายง่ายและให้คะแนนเด่น",
        "highlight": "ยอดนิยม",
    },
    {
        "display_order": 2,
        "sku": "CLD-02",
        "name": "คลอดต้า 2",
        "price": 1190.00,
        "pv": 200.00,
        "description": "แพ็กขนาดกลางสำหรับลูกค้าที่ต้องการความคุ้มค่า",
        "highlight": "กำไรดี",
    },
    {
        "display_order": 3,
        "sku": "CLD-03",
        "name": "คลอดต้า 3",
        "price": 1990.00,
        "pv": 200.00,
        "description": "แพ็กเจาะกลุ่มที่ต้องการเร่งยอดและคะแนน",
        "highlight": "เร่ง PV",
    },
    {
        "display_order": 4,
        "sku": "COFFEE",
        "name": "กาแฟคัลเลอร์คอฟฟี่พลัส",
        "price": 219.00,
        "pv": 33.24,
        "description": "สินค้าซื้อซ้ำง่าย ใช้เติมยอดระหว่างออเดอร์",
        "highlight": "เติมยอด",
    },
    {
        "display_order": 5,
        "sku": "BAG",
        "name": "โค้ดบังสาถี",
        "price": 350.00,
        "pv": 50.00,
        "description": "อุปกรณ์เสริมสำหรับใช้งานหน้าร้านหรือออกบูธ",
        "highlight": "เสริมภาพลักษณ์",
    },
    {
        "display_order": 6,
        "sku": "SERUM",
        "name": "PL โกลด์คอลลาเจนเซรั่ม",
        "price": 558.00,
        "pv": 50.00,
        "description": "สินค้าดูพรีเมียม เหมาะกับการปิดการขายหน้าจอเดียว",
        "highlight": "พรีเมียม",
    },
    {
        "display_order": 7,
        "sku": "BOOKING",
        "name": "ค่ามัดจำ",
        "price": 100.00,
        "pv": 0.00,
        "description": "เก็บยอดได้ทันทีโดยไม่กระทบคะแนน",
        "highlight": "ไม่มี PV",
    },
    {
        "display_order": 8,
        "sku": "MEMBER",
        "name": "ชุดสมัครสมาชิก",
        "price": 599.00,
        "pv": 0.00,
        "description": "เปิดรหัสใหม่พร้อมเอกสารและสื่อประกอบ",
        "highlight": "เริ่มทีม",
    },
]
